[package]
authors = ["smtc2web Contributors"]
description = "An software can let OBS show playing media."
edition = "2024"
name = "smtc2web"
version = "0.6.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["custom-protocol"]
dev = []
custom-protocol = ["tauri/custom-protocol"]

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
crate-type = ["staticlib", "cdylib", "rlib"]
name = "smtc2web_lib"

[build-dependencies]
tauri-build = {version = "2", features = [] }

[dependencies]
base64 = "0.22"
dirs = "5.0"
mime_guess = "2.0"
open = "5.0"
notify = "6"
rust-embed = "8.0"
serde = {version = "1", features = ["derive"] }
serde_json = "1"
tauri = {version = "2", features = ["tray-icon", "image-png"] }

tokio = {version = "1", features = ["rt-multi-thread", "macros", "signal", "process"] }
toml = "0.8"
warp = "0.3"
chrono = "0.4"
named-lock = "0.4"

zip = "0.6"

clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
tauri-plugin-updater = "2"
ttf-parser = "0.25"
tokio-stream = { version = "0.1", features = ["sync"] }

[target.'cfg(target_os = "windows")'.dependencies.windows]
features = [
  "Foundation",
  "Foundation_Collections",
  "Media_Control",
  "Storage",
  "Storage_Streams",
  "Management_Deployment",
  "ApplicationModel",
  "System",
  "Win32_System_WinRT",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Shell",
  "Win32_System_Console",
  "Win32_System_Threading",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_System_ProcessStatus",
  "Win32_Foundation",
  "Win32_Globalization",
  "Win32_Security",
  "Win32_System_Registry",
]
version = "0.58"

[target.'cfg(target_os = "linux")'.dependencies]
mpris = "2.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "core"
harness = false
