// FontAwesome configuration
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faMusic,
  faPaintBrush,
  faGear,
  faImage,
  faHourglass,
  faUpload,
  faTrash,
  faCheckCircle,
  faTimes,
  faExclamationCircle,
  faExclamationTriangle,
  faInfoCircle,
  faSpinner,
  faCheck,
  faFloppyDisk,
  faDownload,
  faRotate,
  faCircleUp,
  faCodeBranch,
  faCopy,
} from "@fortawesome/free-solid-svg-icons";

// Add icons to the library
library.add(
  faMusic,
  faPaintBrush,
  faGear,
  faImage,
  faHourglass,
  faUpload,
  faTrash,
  faCheckCircle,
  faTimes,
  faExclamationCircle,
  faExclamationTriangle,
  faInfoCircle,
  faSpinner,
  faCheck,
  faFloppyDisk,
  faDownload,
  faRotate,
  faCircleUp,
  faCodeBranch,
  faCopy,
);
